export const state = {
  theme: localStorage.getItem('theme') || 'light', // light | dark | auto
  lang: localStorage.getItem('lang') || 'en',      // en | ar | tr | ru
  currentUserId: 1,
  useRealData: true, // Switch to real API data instead of mock
  apiBaseUrl: 'http://localhost:4000', // Backend API URL
};

export const i18n = {
  en: {
    dashboard:'Dashboard', leads:'Leads', tasks:'Tasks', users:'Users', roles:'Roles', reports:'Reports', assign:'Assignment',
    theme:'Theme', language:'Language', auto:'Auto', light:'Light', dark:'Dark',
    kpis:{ total:'Total Leads', newToday:'New Today', inProgress:'In Progress', converted:'Converted', openTasks:'Open Tasks' },
    charts:{ bySource:'Leads by Source', byStatus:'Leads by Status', byGender:'Leads by Gender', byDegree:'Leads by Degree', last7:'Leads – last 7 days', recent:'Recent Leads' },
    labels:{ name:'Name', email:'Email', phone:'Phone', source:'Source', status:'Status', assignee:'Assignee', actions:'Actions', open:'Open', edit:'Edit', nationality:'Nationality', residence:'Residence', city:'City', gender:'Gender', program:'Program', degree:'Degree', type:'Type', due:'Due' },
    filters:{ search:'Search', all:'All statuses', allSources:'All sources', allAssignees:'All assignees', allTypes:'All types', allCities:'All cities', allGenders:'All genders' },
    import:'Import', export:'Export', add:'Add', save:'Save', cancel:'Cancel', back:'Back', quickTask:'Quick Task', markDone:'Mark as Done', notFound:'not found',
    roleManagement: 'Role Management',
    showInactiveRoles: 'Show Inactive Roles',
    addNewRole: 'Add New Role',
    noRolesFound: 'No roles found',
    active: 'Active',
    inactive: 'Inactive',
    editRole: 'Edit Role',
    deleteRole: 'Delete Role',
    activateRole: 'Activate',
    deactivateRole: 'Deactivate',
    noDescription: 'No description provided',
    users: 'Users',
    permissions: 'Permissions',
    canReceiveTasks: 'Can Receive Tasks',
    yes: 'Yes',
    no: 'No',
    keyPermissions: 'Key Permissions',
    noPermissionsAssigned: 'No permissions assigned',
    roleName: 'Role Name',
    description: 'Description',
    enterRoleName: 'Enter role name',
    roleDescription: 'Brief description of this role\'s purpose',
    canReceiveAssignments: 'Can Receive Assignments',
    createRole: 'Create Role',
    updateRole: 'Update Role',
    view: 'View',
    create: 'Create',
    edit: 'Edit',
    delete: 'Delete',
    manage: 'Manage',
    assign: 'Assign',
    none: 'None',
    own: 'Own Only',
    team: 'Team',
    all: 'All',
    confirmDelete: 'Are you sure you want to delete the role',
    confirmActivate: 'Are you sure you want to activate this role?',
    confirmDeactivate: 'Are you sure you want to deactivate this role?',
    cannotUndo: 'This action cannot be undone.',
    failedToSave: 'Failed to save role',
    failedToDelete: 'Failed to delete role',
    name:'Name', source:'Source', nationality:'Nationality', assignee:'Assignee', status:'Status', createdAt:'Created At', city:'City', gender:'Gender',
    allSources:'All Sources', allNationalities:'All Nationalities', allAssignees:'All Assignees', allStatuses:'All Statuses', allCities:'All Cities', allGenders:'All Genders',
    filter:'Filter', noResults:'No results found.', unassigned:'Unassigned', fromDate:'From Date', toDate:'To Date', clear:'Clear',
    addLead:'Add Lead', importLeads:'Import Leads', exportLeads:'Export Leads', quickTask:'Quick Task', markDone:'Mark as Done',
    new:'New', in_progress:'In Progress', converted:'Converted', rejected:'Rejected',
    leadInfo:'Lead Info', contact:'Contact', history:'History', tasks:'Tasks',
  },
  ar: {
    dashboard:'لوحة التحكم', leads:'العملاء المحتملون', tasks:'المهام', users:'المستخدمون', roles:'الصلاحيات', reports:'التقارير', assign:'التوزيع',
    theme:'السمة', language:'اللغة', auto:'تلقائي', light:'فاتح', dark:'داكن',
    kpis:{ total:'إجمالي العملاء', newToday:'المضاف اليوم', inProgress:'قيد المتابعة', converted:'المحوّلون', openTasks:'مهام مفتوحة' },
    charts:{ bySource:'العملاء حسب المصدر', byStatus:'العملاء حسب الحالة', byGender:'العملاء حسب النوع', byDegree:'العملاء حسب الدرجة', last7:'العملاء – آخر 7 أيام', recent:'أحدث العملاء' },
    labels:{ name:'الاسم', email:'البريد', phone:'التليفون', source:'المصدر', status:'الحالة', assignee:'المسؤول', actions:'إجراء', open:'فتح', edit:'تعديل', nationality:'الجنسية', residence:'بلد الإقامة', city:'المدينة', gender:'النوع', program:'البرنامج', degree:'الدرجة', type:'نوع المهمة', due:'الموعد' },
    filters:{ search:'بحث', all:'كل الحالات', allSources:'كل المصادر', allAssignees:'كل المسؤولين', allTypes:'كل الأنواع', allCities:'كل المدن', allGenders:'كل الأنواع' },
    import:'استيراد', export:'تصدير', add:'إضافة', save:'حفظ', cancel:'إلغاء', back:'رجوع', quickTask:'مهمة سريعة', markDone:'إنهاء المهمة', notFound:'غير موجود',
    roleManagement: 'إدارة الأدوار',
    showInactiveRoles: 'عرض الأدوار المعطلة',
    addNewRole: 'إضافة دور جديد',
    noRolesFound: 'لا توجد أدوار',
    active: 'نشط',
    inactive: 'معطل',
    editRole: 'تعديل الدور',
    deleteRole: 'حذف الدور',
    activateRole: 'تفعيل',
    deactivateRole: 'تعطيل',
    noDescription: 'لا يوجد وصف',
    users: 'المستخدمين',
    permissions: 'الصلاحيات',
    canReceiveTasks: 'يمكن تلقي المهام',
    yes: 'نعم',
    no: 'لا',
    keyPermissions: 'الصلاحيات الرئيسية',
    noPermissionsAssigned: 'لا توجد صلاحيات',
    roleName: 'اسم الدور',
    description: 'الوصف',
    enterRoleName: 'أدخل اسم الدور',
    roleDescription: 'وصف مختصر لهذا الدور',
    canReceiveAssignments: 'يمكن تلقي المهام',
    createRole: 'إنشاء الدور',
    updateRole: 'تحديث الدور',
    view: 'عرض',
    create: 'إنشاء',
    edit: 'تعديل',
    delete: 'حذف',
    manage: 'إدارة',
    assign: 'تكليف',
    none: 'لا شيء',
    own: 'الخاص فقط',
    team: 'الفريق',
    all: 'الكل',
    confirmDelete: 'هل أنت متأكد من حذف الدور',
    confirmActivate: 'هل أنت متأكد من تفعيل هذا الدور؟',
    confirmDeactivate: 'هل أنت متأكد من تعطيل هذا الدور؟',
    cannotUndo: 'لا يمكن التراجع عن هذا الإجراء.',
    failedToSave: 'فشل في حفظ الدور',
    failedToDelete: 'فشل في حذف الدور',
    name:'الاسم', source:'المصدر', nationality:'الجنسية', assignee:'المسؤول', status:'الحالة', createdAt:'تاريخ الإنشاء', city:'المدينة', gender:'النوع',
    allSources:'كل المصادر', allNationalities:'كل الجنسيات', allAssignees:'كل المسؤولين', allStatuses:'كل الحالات', allCities:'كل المدن', allGenders:'كل الأنواع',
    filter:'فلترة', noResults:'لا توجد نتائج.', unassigned:'غير معين', fromDate:'من تاريخ', toDate:'إلى تاريخ', clear:'مسح',
    addLead:'إضافة عميل', importLeads:'استيراد عملاء', exportLeads:'تصدير عملاء', quickTask:'مهمة سريعة', markDone:'إنهاء المهمة',
    new:'جديد', in_progress:'قيد المتابعة', converted:'تم التحويل', rejected:'مرفوض',
    leadInfo:'بيانات العميل', contact:'التواصل', history:'السجل', tasks:'المهام',
  },
  tr: {
    dashboard:'Pano', leads:'Adaylar', tasks:'Görevler', users:'Kullanıcılar', roles:'Roller', reports:'Raporlar', assign:'Atama',
    theme:'Tema', language:'Dil', auto:'Oto', light:'Açık', dark:'Koyu',
    kpis:{ total:'Toplam Aday', newToday:'Bugün Yeni', inProgress:'Devam', converted:'Dönüştürülen', openTasks:'Açık Görev' },
    charts:{ bySource:'Kaynağa göre', byStatus:'Duruma göre adaylar', byGender:'Cinsiyete göre adaylar', byDegree:'Dereceye göre adaylar', last7:'Son 7 gün', recent:'Son adaylar' },
    labels:{ name:'Ad', email:'E-posta', phone:'Telefon', source:'Kaynak', status:'Durum', assignee:'Atanan', actions:'İşlem', open:'Aç', edit:'Düzenle', nationality:'Uyruk', residence:'İkamet', city:'Şehir', gender:'Cinsiyet', program:'Program', degree:'Derece', type:'Tür', due:'Tarih' },
    filters:{ search:'Ara', all:'Tüm durumlar', allSources:'Tüm kaynaklar', allAssignees:'Tüm atanlar', allTypes:'Tüm türler', allCities:'Tüm şehirler', allGenders:'Tüm cinsiyetler' },
    import:'İçe aktar', export:'Dışa aktar', add:'Ekle', save:'Kaydet', cancel:'İptal', back:'Geri', quickTask:'Hızlı Görev', markDone:'Tamam', notFound:'bulunamadı',
    roleManagement: 'Rol Yönetimi',
    showInactiveRoles: 'Etkin Olmayan Rolleri Göster',
    addNewRole: 'Yeni Rol Ekle',
    noRolesFound: 'Rol bulunamadı',
    active: 'Etkin',
    inactive: 'Etkin Olmayan',
    editRole: 'Rolü Düzenle',
    deleteRole: 'Rolü Sil',
    activateRole: 'Etkinleştir',
    deactivateRole: 'Etkinleştirme',
    noDescription: 'Açıklama bulunamadı',
    users: 'Kullanıcılar',
    permissions: 'İzinler',
    canReceiveTasks: 'Görev alabilir',
    yes: 'Evet',
    no: 'Hayır',
    keyPermissions: 'Ana İzinler',
    noPermissionsAssigned: 'İzin atanmadı',
    roleName: 'Rol Adı',
    description: 'Açıklama',
    enterRoleName: 'Rol adını girin',
    roleDescription: 'Bu rolün amacı hakkında kısa açıklama',
    canReceiveAssignments: 'Görev alabilir',
    createRole: 'Rol Oluştur',
    updateRole: 'Rol Güncelle',
    view: 'Görüntüle',
    create: 'Oluştur',
    edit: 'Düzenle',
    delete: 'Sil',
    manage: 'Yönet',
    assign: 'Ata',
    none: 'Hiçbiri',
    own: 'Sadece Kendi',
    team: 'Takım',
    all: 'Tümü',
    confirmDelete: 'Rolü silmek istediğinizden emin misiniz?',
    confirmActivate: 'Bu rolü etkinleştirmek istediğinizden emin misiniz?',
    confirmDeactivate: 'Bu rolü devre dışı bırakmak istediğinizden emin misiniz?',
    cannotUndo: 'Bu işlemi geri alamazsınız.',
    failedToSave: 'Rolü kaydetme başarısız',
    failedToDelete: 'Rolü silme başarısız',
    name:'İsim', source:'Kaynak', nationality:'Uyruk', assignee:'Atanan', status:'Durum', createdAt:'Oluşturma Tarihi', city:'Şehir', gender:'Cinsiyet',
    allSources:'Tüm Kaynaklar', allNationalities:'Tüm Uyruklar', allAssignees:'Tüm Atananlar', allStatuses:'Tüm Durumlar', allCities:'Tüm Şehirler', allGenders:'Tüm Cinsiyetler',
    filter:'Filtrele', noResults:'Sonuç bulunamadı.', unassigned:'Atanmamış', fromDate:'Başlangıç', toDate:'Bitiş', clear:'Temizle',
    addLead:'Aday Ekle', importLeads:'İçe Aktar', exportLeads:'Dışa Aktar', quickTask:'Hızlı Görev', markDone:'Tamamlandı İşaretle',
    new:'Yeni', in_progress:'Devam Ediyor', converted:'Dönüştürüldü', rejected:'Reddedildi',
    leadInfo:'Aday Bilgisi', contact:'İletişim', history:'Geçmiş', tasks:'Görevler',
  },
  ru: {
    dashboard:'Панель', leads:'Лиды', tasks:'Задачи', users:'Пользователи', roles:'Роли', reports:'Отчёты', assign:'Назначение',
    theme:'Тема', language:'Язык', auto:'Авто', light:'Светлая', dark:'Тёмная',
    kpis:{ total:'Всего лидов', newToday:'Новые сегодня', inProgress:'В работе', converted:'Конверт.', openTasks:'Открытые задачи' },
    charts:{ bySource:'Лиды по источнику', byStatus:'Лиды по статусу', byGender:'Лиды по полу', byDegree:'Лиды по степени', last7:'За 7 дней', recent:'Недавние лиды' },
    labels:{ name:'Имя', email:'Почта', phone:'Телефон', source:'Источник', status:'Статус', assignee:'Ответственный', actions:'Действия', open:'Открыть', edit:'Править', nationality:'Национальность', residence:'Страна проживания', city:'Город', gender:'Пол', program:'Программа', degree:'Степень', type:'Тип', due:'Срок' },
    filters:{ search:'Поиск', all:'Все статусы', allSources:'Все источники', allAssignees:'Все ответственные', allTypes:'Все типы', allCities:'Все города', allGenders:'Все полы' },
    import:'Импорт', export:'Экспорт', add:'Добавить', save:'Сохранить', cancel:'Отмена', back:'Назад', quickTask:'Быстрая задача', markDone:'Готово', notFound:'не найден',
    roleManagement: 'Управление ролями',
    showInactiveRoles: 'Показать неактивные роли',
    addNewRole: 'Добавить новую роль',
    noRolesFound: 'Роли не найдены',
    active: 'Активный',
    inactive: 'Неактивный',
    editRole: 'Редактировать роль',
    deleteRole: 'Удалить роль',
    activateRole: 'Активировать',
    deactivateRole: 'Деактивировать',
    noDescription: 'Описание не найдено',
    users: 'Пользователи',
    permissions: 'Разрешения',
    canReceiveTasks: 'Может получать задачи',
    yes: 'Да',
    no: 'Нет',
    keyPermissions: 'Ключевые разрешения',
    noPermissionsAssigned: 'Разрешения не назначены',
    roleName: 'Название роли',
    description: 'Описание',
    enterRoleName: 'Введите название роли',
    roleDescription: 'Краткое описание цели этой роли',
    canReceiveAssignments: 'Может получать задачи',
    createRole: 'Создать роль',
    updateRole: 'Обновить роль',
    view: 'Просмотр',
    create: 'Создать',
    edit: 'Редактировать',
    delete: 'Удалить',
    manage: 'Управлять',
    assign: 'Назначить',
    none: 'Нет',
    own: 'Только свои',
    team: 'Команда',
    all: 'Все',
    confirmDelete: 'Вы уверены, что хотите удалить роль?',
    confirmActivate: 'Вы уверены, что хотите активировать эту роль?',
    confirmDeactivate: 'Вы уверены, что хотите деактивировать эту роль?',
    cannotUndo: 'Это действие нельзя отменить.',
    failedToSave: 'Не удалось сохранить роль',
    failedToDelete: 'Не удалось удалить роль',
    name:'Имя', source:'Источник', nationality:'Национальность', assignee:'Ответственный', status:'Статус', createdAt:'Дата создания', city:'Город', gender:'Пол',
    allSources:'Все источники', allNationalities:'Все национальности', allAssignees:'Все ответственные', allStatuses:'Все статусы', allCities:'Все города', allGenders:'Все полы',
    filter:'Фильтр', noResults:'Ничего не найдено.', unassigned:'Не назначен', fromDate:'С даты', toDate:'По дату', clear:'Очистить',
    addLead:'Добавить лид', importLeads:'Импорт лидов', exportLeads:'Экспорт лидов', quickTask:'Быстрая задача', markDone:'Отметить как выполненное',
    new:'Новый', in_progress:'В процессе', converted:'Конвертирован', rejected:'Отклонен',
    leadInfo:'Информация о лиде', contact:'Контакт', history:'История', tasks:'Задачи',
  }
};

export function t(key) {
  const d = i18n[state.lang] || i18n.en;
  return key.split('.').reduce((o, k) => (o && o[k]) ?? null, d) || key;
}

export function applyTheme() {
  const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
  const wantDark = state.theme === 'dark' || (state.theme === 'auto' && prefersDark);
  document.documentElement.classList.toggle('dark', wantDark);
}

export function applyLang() {
  document.documentElement.lang = state.lang;
  document.documentElement.dir = state.lang === 'ar' ? 'rtl' : 'ltr';
}

// Get current user data
export function getCurrentUser() {
  // For now, return a mock user based on currentUserId
  // In a real app, this would fetch from authentication state
  const users = window.usersData || [];
  return users.find(u => u.id === state.currentUserId) || {
    id: state.currentUserId,
    name: 'Current User',
    email: 'user@example.com',
    roles: ['admin']
  };
}
