version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leadapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build: .
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/leadapp?schema=public
      - JWT_SECRET=replace_me
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: sh -c "npm run prisma:deploy && npm run start"
volumes:
  pgdata:
